INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0001', '國立政治大學', 'National Chengchi University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0002', '國立清華大學', 'National Tsing Hua University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0003', '國立臺灣大學', 'National Taiwan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0004', '國立臺灣師範大學', 'National Taiwan Normal University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0005', '國立成功大學', 'National Cheng Kung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0006', '國立中興大學', 'National Chung Hsing University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0007', '國立陽明交通大學', 'National Yang Ming Chiao Tung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0008', '國立中央大學', 'National Central University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0009', '國立中山大學', 'National Sun Yat-sen University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0012', '國立臺灣海洋大學', 'National Taiwan Ocean University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0013', '國立中正大學', 'National Chung Cheng University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0014', '國立高雄師範大學', 'National Kaohsiung Normal University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0015', '國立彰化師範大學', 'National Changhua University of Education', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0017', '國立臺北大學', 'National Taipei University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0018', '國立嘉義大學', 'National Chiayi University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0019', '國立高雄大學', 'National University of Kaohsiung', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0020', '國立東華大學', 'National Dong Hwa University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0021', '國立暨南國際大學', 'National Chi Nan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0022', '國立臺灣科技大學', 'National Taiwan University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0023', '國立雲林科技大學', 'National Yunlin University of Science & Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0024', '國立屏東科技大學', 'National Pingtung University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0025', '國立臺北科技大學', 'National Taipei University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0028', '國立臺北藝術大學', 'Taipei National University of the Arts', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0029', '國立臺灣藝術大學', 'National Taiwan University of Arts', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0030', '國立臺東大學', 'National Taitung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0031', '國立宜蘭大學', 'National Ilan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0032', '國立聯合大學', 'National United University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0033', '國立虎尾科技大學', 'National Formosa University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0035', '國立臺南藝術大學', 'Tainan National University of the Arts', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0036', '國立臺南大學', 'National University of Tainan', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0037', '國立臺北教育大學', 'National Taipei University of Education', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0039', '國立臺中教育大學', 'National Taichung University of Education', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0042', '國立澎湖科技大學', 'National Penghu University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0043', '國立勤益科技大學', 'National Chin-Yi University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0044', '國立體育大學', 'National Taiwan Sport University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0046', '國立臺北護理健康大學', 'National Taipei University of Nursing and Health Sciences', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0047', '國立高雄餐旅大學', 'National Kaohsiung University of Hospitality and Tourism', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0048', '國立金門大學', 'National Quemoy University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0049', '國立臺灣體育運動大學', 'National Taiwan University of Sport', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0050', '國立臺中科技大學', 'National  Taichung University Of  Science And Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0051', '國立臺北商業大學', 'National Taipei University of  Business', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0052', '國立屏東大學', 'National Pingtung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0053', '國立高雄科技大學', 'National Kaohsiung University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0144', '國立臺灣戲曲學院', 'National Taiwan College of Performing Arts', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0221', '國立臺南護理專科學校', 'National Tainan Junior College of Nursing', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0222', '國立臺東專科學校', 'National Taitung Junior College', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0A01', '國立空中大學', 'National Open University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1001', '東海大學', 'Tunghai University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1002', '輔仁大學', 'Fu Jen Catholic University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1003', '東吳大學', 'Soochow University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1004', '中原大學', 'Chung Yuan Christian University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1005', '淡江大學學校財團法人淡江大學', 'Tamkang University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1006', '中國文化大學', 'Chinese Culture University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1007', '逢甲大學', 'Feng Chia University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1008', '靜宜大學', 'Providence University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1009', '長庚大學', 'Chang Gung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1010', '元智大學', 'Yuan Ze University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1011', '中華大學學校財團法人中華大學', 'Chung Hua University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1012', '大葉大學', 'Da-Yeh University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1013', '華梵大學', 'Huafan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1014', '義守大學', 'I-Shou University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1015', '世新大學', 'Shih Hsin University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1016', '銘傳大學', 'Ming Chuan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1017', '實踐大學', 'Shih Chien University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1018', '朝陽科技大學', 'Chaoyang University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1019', '高雄醫學大學', 'Kaohsiung Medical University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1020', '南華大學', 'Nanhua university', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1021', '真理大學', 'Aletheia University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1022', '大同大學', 'Tatung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1023', '南臺學校財團法人南臺科技大學', 'Southern Taiwan University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1024', '崑山科技大學', 'Kun Shan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1025', '嘉藥學校財團法人嘉南藥理大學', 'Chia Nan University of Pharmacy & Science', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1026', '樹德科技大學', 'Shu-Te University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1027', '慈濟學校財團法人慈濟大學', 'Tzu Chi University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1028', '臺北醫學大學', 'Taipei Medical University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1029', '中山醫學大學', 'Chung Shan Medical University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1030', '龍華科技大學', 'Lunghwa University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1031', '輔英科技大學', 'Fooyin University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1032', '明新學校財團法人明新科技大學', 'Minghsin University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1033', '長榮大學', 'Chang Jung Christian University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1034', '弘光科技大學', 'Hungkuang University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1035', '中國醫藥大學', 'China Medical University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1036', '健行學校財團法人健行科技大學', 'Chien Hsin University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1037', '正修學校財團法人正修科技大學', 'Cheng Shiu University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1038', '萬能學校財團法人萬能科技大學', 'Vanung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1039', '玄奘大學', 'Hsuan Chuang University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1040', '建國科技大學', 'Chienkuo Technology University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1041', '明志科技大學', 'Ming Chi University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1042', '高苑科技大學', 'Kao Yuan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1043', '大仁科技大學', 'Tajen University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1044', '聖約翰科技大學', 'St. John’s University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1045', '嶺東科技大學', 'Ling Tung University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1046', '中國科技大學', 'China University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1047', '中臺科技大學', 'Central Taiwan University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1048', '亞洲大學', 'Asia University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1049', '開南大學', 'Kainan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1050', '佛光大學', 'Fo Guang University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1051', '台南家專學校財團法人台南應用科技大學', 'Tainan School of Home Economics Foundation at Tainan University of Technology',
        NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1052', '遠東科技大學', 'Far East University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1053', '光宇學校財團法人元培醫事科技大學', 'Yuanpei University of Medical Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1054', '景文科技大學', 'Jinwen University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1055', '中華醫事科技大學', 'Chung Hwa University of Medical Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1056', '東南科技大學', 'Tungnan University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1057', '德明財經科技大學', 'Takming University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1058', '明道學校財團法人明道大學', 'MingDao University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1060', '南開科技大學', 'Nan Kai University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1061', '中華學校財團法人中華科技大學', 'China University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1062', '僑光科技大學', 'Overseas Chinese University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1063', '廣亞學校財團法人育達科技大學', 'Yu Da University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1064', '美和學校財團法人美和科技大學', 'Meiho University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1065', '吳鳳科技大學', 'WuFeng University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1066', '環球學校財團法人環球科技大學', 'TransWorld University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1067', '台灣首府學校財團法人台灣首府大學', 'Taiwan Shoufu University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1068', '中州學校財團法人中州科技大學', 'Chung Chou University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1069', '修平學校財團法人修平科技大學', 'Hsiuping University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1070', '長庚學校財團法人長庚科技大學', 'Chang Gung University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1071', '城市學校財團法人臺北城市科技大學', 'Taipei City University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1072', '大華學校財團法人敏實科技大學', 'Minth University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1073', '醒吾學校財團法人醒吾科技大學', 'Hsing Wu University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1075', '文藻學校財團法人文藻外語大學', 'Wenzao Ursuline University of Languages', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1076', '華夏學校財團法人華夏科技大學', 'Hwa Hsia University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1077', '慈濟學校財團法人慈濟科技大學', 'Tzu Chi University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1078', '致理學校財團法人致理科技大學', 'Chihlee University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1079', '康寧學校財團法人康寧大學', 'University of Kang Ning', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1080', '宏國學校財團法人宏國德霖科技大學', 'Hungkuo Delin University of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1081', '東方學校財團法人東方設計大學', 'TungFang Design University', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1082', '崇右學校財團法人崇右影藝科技大學', 'Chungyu University of Film and Arts', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1083', '台北海洋學校財團法人台北海洋科技大學', 'Taipei University of Marine Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1084', '亞東學校財團法人亞東科技大學', 'Asia Eastern University of Science and Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1125', '中信金融管理學院', 'CTBC Business School', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1148', '大漢學校財團法人大漢技術學院', 'Dahan Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1159', '和春技術學院', 'Fortune Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1168', '南亞科技學校財團法人南亞技術學院', 'Nanya Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1182', '蘭陽技術學院', 'Lan Yang Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1183', '黎明技術學院', 'Lee-Ming Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1185', '經國管理暨健康學院', 'CHING KUO INSTITUTE OF MANAGEMENT AND HEALTH', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1188', '大同技術學院', 'Tatung Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1195', '馬偕學校財團法人馬偕醫學院', 'MacKay Medical College', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1196', '法鼓學校財團法人法鼓文理學院', 'Dharma Drum Institute of Liberal Art', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1282', '馬偕學校財團法人馬偕醫護管理專科學校', 'MacKay Junior College of Medicine, Nursing, and Management', NULL, NULL, NULL,
        NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1283', '仁德醫護管理專科學校', 'Jen-Teh Junior College of Medicine, Nursing and Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1284', '樹人醫護管理專科學校', 'Shu-Zen Junior College of Medicine and Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1285', '慈惠醫護管理專科學校', 'TZU HUI Institute of Technology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1286', '耕莘健康管理專科學校', 'Cardinal Tien Junior College of Healthcare And Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1287', '敏惠醫護管理專科學校', 'Min-Hwei Junior College of Health Care Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1289', '育英醫護管理專科學校', 'Yuh-Ing Junior College of Health Care & Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1291', '聖母醫護管理專科學校', 'St. Mary´s Junior College of Medicine, Nursing and Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1292', '新生醫護管理專科學校', 'Hsin Sheng Junior College of Medical Care and Management', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1293', '崇仁醫護管理專科學校', 'Chung-Jen Junior College of Nursing, Health Sciences and Management', NULL, NULL, NULL,
        NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R02', '學校財團法人中華浸信會基督教台灣浸會神學院', 'Taiwan Baptist Christian Seminary', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R03', '臺北基督學院', 'Christ''s College Taipei', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R04', '財團法人一貫道天皇基金會一貫道天皇學院', 'I-Kuan Tao College', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R05', '台神學校財團法人台灣神學研究學院', 'Taiwan Graduate School of Theology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R06', '一貫道崇德學院', 'I.K.T. Chong-De School', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R07', '台灣基督長老教會南神神學院', 'Tainan Theological College', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R08', '基督教華神學校財團法人中華福音神學研究學院', 'China Evangelical Graduate School of Theology', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R09', '唯心聖教學院', 'Weixin Shengjiao College', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3002', '臺北市立大學', 'University of Taipei', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL (ID, ZH_NAME, EN_NAME, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3A01', '高雄市立空中大學', 'Open University of Kaohsiung', NULL, NULL, NULL, NULL);

INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0001', '11605', '臺北市', '文山區', '臺北市文山區,指南路2段64號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0002', '30013', '新竹市', '新竹市', '新竹市光復路2段101號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0003', '10617', '臺北市', '大安區', '臺北市大安區,羅斯福路4段1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0004', '10610', '臺北市', '大安區', '臺北市大安區,和平東路1段162號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0005', '70101', '臺南市', '東　區', '臺南市東區,大學路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0006', '40227', '臺中市', '南　區', '台中市南區,興大路145號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0007', '30010', '新竹市', '新竹市', '新竹市大學路1001號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0008', '32001', '桃園市', '中壢區', '桃園市中壢區,中大路300號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0009', '80424', '高雄市', '鼓山區', '高雄市鼓山區,蓮海路70號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0012', '20224', '基隆市', '中正區', '基隆市北寧路2號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0013', '62102', '嘉義縣', '民雄鄉', '嘉義縣民雄鄉大學路168號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0014', '80201', '高雄市', '苓雅區', '高雄市苓雅區,和平一路116號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0015', '50007', '彰化縣', '彰化市', '彰化市進德路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0017', '23741', '新北市', '三峽區', '新北市三峽區,大學路151號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0018', '60004', '嘉義市', '嘉義市', '嘉義市東區,鹿寮里學府路300號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0019', '81148', '高雄市', '楠梓區', '高雄市楠梓區,高雄大學路700號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0020', '97401', '花蓮縣', '壽豐鄉', '花蓮縣壽豐鄉志學村大學路2段1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0021', '54561', '南投縣', '埔里鎮', '南投縣埔里鎮大學路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0022', '10607', '臺北市', '大安區', '臺北市大安區,基隆路四段43號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0023', '640301', '雲林縣', '斗六市', '雲林縣斗六市大學路三段123號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0024', '91201', '屏東縣', '內埔鄉', '屏東縣內埔鄉老埤村學府路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0025', '10608', '臺北市', '大安區', '臺北市忠孝東路三段1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0028', '11201', '臺北市', '北投區', '臺北市北投區,學園路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0029', '22058', '新北市', '板橋區', '新北市板橋區,大觀路1段59號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0030', '95092', '臺東縣', '臺東市', '臺東市大學路二段369號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0031', '26047', '宜蘭縣', '宜蘭市', '宜蘭縣宜蘭市神農路1段1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0032', '36063', '苗栗縣', '苗栗市', '苗栗縣苗栗市南勢里聯大二號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0033', '63201', '雲林縣', '虎尾鎮', '雲林縣虎尾鎮文化路64號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0035', '72045', '臺南市', '官田區', '臺南市官田區,大崎里大崎66號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0036', '70005', '臺南市', '中西區', '臺南市中西區,樹林街2段33號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0037', '10671', '臺北市', '大安區', '臺北市和平東路2段134號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0039', '40306', '臺中市', '西　區', '臺中市西區,民生路140號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0042', '88046', '澎湖縣', '馬公市', '澎湖縣馬公市六合路300號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0043', '41170', '臺中市', '太平區', '臺中市太平區,坪林里中山路二段57號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0044', '33301', '桃園市', '龜山區', '桃園市龜山區,文化一路250號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0046', '11219', '臺北市', '北投區', '臺北市北投區,明德路365號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0047', '81271', '高雄市', '小港區', '高雄市小港區,松和路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0048', '89250', '金門縣', '金寧鄉', '金門縣金寧鄉大學路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0049', '40404', '臺中市', '北　區', '臺中市北區,雙十路1段16號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0050', '40401', '臺中市', '北區', '臺中巿北區,三民路三段129號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0051', '10051', '臺北市', '中正區', '臺北市中正區,濟南路一段321號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0052', '90003', '屏東縣', '屏東市', '屏東市民生路4-18號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0053', '80778', '高雄市', '三民區', '高雄市三民區,建工路415號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0144', '11464', '臺北市', '內湖區', '臺北市內湖區,內湖路二段177號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0221', '70043', '臺南市', '中西區', '臺南市中西區,民族路二段78號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0222', '95045', '臺東縣', '臺東市', '臺東縣臺東市正氣北路911號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0A01', '24701', '新北市', '蘆洲區', '新北市蘆洲區,中正路 172 號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1001', '40704', '臺中市', '西屯區', '臺中市西屯區,臺灣大道4段1727號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1002', '24205', '新北市', '新莊區', '新北市新莊區,中正路510號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1003', '11102', '臺北市', '士林區', '臺北市士林區,臨溪路70號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1004', '32023', '桃園市', '中壢區', '桃園市中壢區,中北路200號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1005', '25137', '新北市', '淡水區', '新北市淡水區,英專路151號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1006', '11114', '臺北市', '士林區', '臺北市士林區,華岡路55號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1007', '40724', '臺中市', '西屯區', '臺中市西屯區,文華路100號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1008', '43301', '臺中市', '沙鹿區', '臺中市沙鹿區,中棲路200號(臺中市沙鹿區,臺灣大道7段200號)', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1009', '33302', '桃園市', '龜山區', '桃園市龜山區,文化一路259號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1010', '32003', '桃園市', '中壢區', '桃園市中壢區,遠東路135號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1011', '30012', '新竹市', '新竹市', '新竹市東香里六鄰五福路2段707號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1012', '51591', '彰化縣', '大村鄉', '彰化縣大村鄉學府路168號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1013', '22301', '新北市', '石碇區', '新北市石碇區,華梵路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1014', '84001', '高雄市', '大樹區', '高雄市大樹區,學城路1段1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1015', '11604', '臺北市', '文山區', '臺北市文山區,木柵路1段17巷1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1016', '11103', '臺北市', '士林區', '臺北市士林區,中山北路5段250號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1017', '10462', '臺北市', '中山區', '臺北市中山區,大直街70號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1018', '41349', '臺中市', '霧峰區', '臺中市霧峰區,吉峰東路168號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1019', '80708', '高雄市', '三民區', '高雄市三民區,十全一路100號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1020', '62248', '嘉義縣', '大林鎮', '嘉義縣大林鎮中坑里10鄰南華路1段55號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1021', '25103', '新北市', '淡水區', '新北市淡水區,真理街32號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1022', '10452', '臺北市', '中山區', '臺北市中山北路3段40號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1023', '71005', '臺南市', '永康區', '臺南市永康區,南臺街1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1024', '710303', '臺南市', '永康區', '臺南市永康區,崑大路195號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1025', '71710', '臺南市', '仁德區', '臺南市仁德區,二仁路一段60號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1026', '82445', '高雄市', '燕巢區', '高雄市燕巢區,橫山路59號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1027', '97004', '花蓮縣', '花蓮市', '花蓮市中央路3段701號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1028', '11031', '臺北市', '信義區', '臺北市信義區,吳興街250號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1029', '40201', '臺中市', '南　區', '臺中市南區,建國北路1段110號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1030', '33306', '桃園市', '龜山區', '桃園市龜山區,萬壽路一段300號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1031', '83102', '高雄市', '大寮區', '高雄市大寮區,進學路151號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1032', '30401', '新竹縣', '新豐鄉', '新竹縣新豐鄉新興路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1033', '71101', '臺南市', '歸仁區', '臺南市歸仁區,長大路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1034', '43302', '臺中市', '沙鹿區', '臺中市沙鹿區,晉江里臺灣大道六段1018號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1035', '40678', '臺中市', '北屯區', '臺中市北屯區,經貿路一段100號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1036', '32097', '桃園市', '中壢區', '桃園市中壢區,健行路229號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1037', '833301', '高雄市', '鳥松區', '高雄市鳥松區,澄清路840號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1038', '320313', '桃園市', '中壢區', '桃園市中壢區,萬能路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1039', '30092', '新竹市', '新竹市', '新竹市香山區,玄奘路48號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1040', '50094', '彰化縣', '彰化市', '彰化縣彰化市介壽北路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1041', '24301', '新北市', '泰山區', '新北市泰山區,貴子里工專路84號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1042', '82151', '高雄市', '路竹區', '高雄市路竹區,中山路1821號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1043', '90741', '屏東縣', '鹽埔鄉', '屏東縣鹽埔鄉維新路20號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1044', '25135', '新北市', '淡水區', '新北市淡水區,淡金路四段499號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1045', '408284', '臺中市', '南屯區', '臺中市南屯區,嶺東路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1046', '11695', '臺北市', '文山區', '臺北市文山區,興隆路三段56號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1047', '40601', '臺中市', '北屯區', '臺中市北屯區,廍子里10鄰廍子路666號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1048', '41354', '臺中市', '霧峰區', '臺中市霧峰區,柳豐路500號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1049', '33857', '桃園市', '蘆竹區', '桃園市蘆竹區,開南路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1050', '26247', '宜蘭縣', '礁溪鄉', '宜蘭縣礁溪鄉林美村林尾路160號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1051', '71002', '臺南市', '永康區', '臺南市永康區,中正路529號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1052', '74448', '臺南市', '新市區', '臺南市新市區,中華路49號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1053', '30015', '新竹市', '香山區', '新竹市元培街306號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1054', '23154', '新北市', '新店區', '新北市新店區,安忠路99號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1055', '71703', '臺南市', '仁德區', '臺南市仁德區,文華一街89號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1056', '22202', '新北市', '深坑區', '新北市深坑區,北深路三段152號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1057', '11451', '臺北市', '內湖區', '臺北市內湖區,環山路一段56號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1058', '52345', '彰化縣', '埤頭鄉', '彰化縣埤頭鄉文化路369號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1060', '54243', '南投縣', '草屯鎮', '南投縣草屯鎮中正路568號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1061', '11581', '臺北市', '南港區', '臺北市南港區,研究院路三段245號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1062', '40721', '臺中市', '西屯區', '臺中市西屯區,僑光路100號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1063', '36143', '苗栗縣', '造橋鄉', '苗栗縣造橋鄉談文村學府路168號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1064', '91202', '屏東縣', '內埔鄉', '屏東縣內埔鄉美和村屏光路23號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1065', '62153', '嘉義縣', '民雄鄉', '嘉義縣民雄鄉建國路二段117號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1066', '64063', '雲林縣', '斗六市', '雲林縣斗六市嘉東里鎮南路1221號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1067', '72153', '臺南市', '麻豆區', '臺南市麻豆區,南勢里168號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1068', '51003', '彰化縣', '員林市', '彰化縣員林市山腳路三段2巷6號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1069', '41280', '臺中市', '大里區', '臺中市大里區,工業路11號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1070', '33303', '桃園市', '龜山區', '桃園市龜山區,文化一路261號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1071', '11202', '臺北市', '北投區', '臺北市北投區,學園路2號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1072', '30740', '新竹縣', '芎林鄉', '新竹縣芎林鄉大華路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1073', '24452', '新北市', '林口區', '新北市林口區,粉寮路一段101號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1075', '80793', '高雄市', '三民區', '高雄市三民區,民族一路900號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1076', '23568', '新北市', '中和區', '新北市中和區,工專路111號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1077', '970302', '花蓮縣', '花蓮市', '花蓮市建國路二段880號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1078', '22050', '新北市', '板橋區', '新北市板橋區,文化路1段313號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1079', '11485', '臺北市', '內湖區', '台北市內湖區,康寧路三段75巷137號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1080', '23654', '新北市', '土城區', '新北市土城區,青雲路380巷1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1081', '82941', '高雄市', '湖內區', '高雄市湖內區,東方路110號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1082', '20103', '基隆市', '信義區', '基隆市信義區,義七路40號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1083', '25172', '新北市', '淡水區', '新北市淡水區,濱海路三段150號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1084', '22061', '新北市', '板橋區', '新北市板橋區,四川路二段58號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1125', '70963', '臺南市', '安南區', '臺南市安南區,台江大道3段600號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1148', '97145', '花蓮縣', '新城鄉', '花蓮縣新城鄉大漢村樹人街1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1159', '83160', '高雄市', '大寮區', '高雄市大寮區,琉球里至學路288號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1168', '32091', '桃園市', '中壢區', '桃園市中壢區,中山東路三段414號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1182', '26141', '宜蘭縣', '頭城鎮', '宜蘭縣頭城鎮復興路79號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1183', '24305', '新北市', '泰山區', '新北市泰山區,泰林路三段22號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1185', '203301', '基隆市', '中山區', '基隆市中山區,復興路336號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1188', '60005', '嘉義市', '東區', '嘉義市東區,彌陀路253號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1195', '25245', '新北市', '三芝區', '新北市三芝區,中正路3段46號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1196', '20842', '新北市', '金山區', '新北市金山區,西湖里法鼓路700號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1282', '252005', '新北市', '三芝區', '新北市三芝區,中正路三段92號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1283', '35664', '苗栗縣', '後龍鎮', '苗栗縣後龍鎮溪洲里7鄰砂崙湖79-9號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1284', '82144', '高雄市', '路竹區', '高雄市路竹區,環球路452號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1285', '92641', '屏東縣', '南州鄉', '屏東縣南州鄉三民路367號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1286', '23143', '新北市', '新店區', '新北市新店區,民族路112號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1287', '73658', '臺南市', '柳營區', '臺南市柳營區,中山東路二段1116號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1289', '80776', '高雄市', '三民區', '高雄市三民區,大昌二路420巷15號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1291', '26647', '宜蘭縣', '三星鄉', '宜蘭縣三星鄉三星路二段265巷100號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1292', '32544', '桃園市', '龍潭區', '桃園市龍潭區,中豐路高平段418號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1293', '62241', '嘉義縣', '大林鎮', '嘉義縣大林鎮湖北里大湖1之10號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R02', '11045', '臺北市', '信義區', '臺北市吳興街394巷1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R03', '25162', '新北市', '淡水區', '新北市淡水區,自強路51號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R04', '84442', '高雄市', '六龜區', '高雄市六龜區,新寮里三民路81號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R05', '11149', '臺北市', '士林區', '台北市士林區,仰德大道二段二巷20號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R06', '54552', '南投縣', '埔里鎮', '南投縣埔里鎮鯉魚路25-8號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R07', '70142', '臺南市', '東　區', '臺南市東區,東門路一段117號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R08', '334025', '桃園市', '八德區', '桃園市八德區,長安街53號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R09', '540022', '南投縣', '南投市', '南投縣南投市文化路705巷667號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3002', '10048', '臺北市', '中正區', '臺北市中正區,愛國西路1號', NULL, NULL, NULL, NULL);
INSERT INTO ADDRESS (ID, POSTAL_CODE, COUNTY, AREA, ADDRESS, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3A01', '81249', '高雄市', '小港區', '高雄市小港區,大業北路436號', NULL, NULL, NULL, NULL);

INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0001', '02-2939-3091', '02-2937-9611', 'http://www.nccu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0002', '03-571-5131', '03-572-4038', 'http://www.nthu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0003', '02-3366-3366', '02-2362-7651', 'http://www.ntu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0004', '02-7749-1111', '無', 'http://www.ntnu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0005', '06-275-7575', '06-276-6462', 'http://www.ncku.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0006', '04-2287-3181', '04-2287-3702', 'http://www.nchu.edu.tw/index1.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0007', '03-571-2121', '03-573-1776', 'http://www.nycu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0008', '03-422-7151', '03-425-4842', 'http://www.ncu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0009', '07-525-2000', '07-525-0227', 'http://www.nsysu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0012', '02-2462-2192', '02-2462-0724', 'http://www.ntou.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0013', '05-272-0411', '05-272-0401', 'http://www.ccu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0014', '07-717-2930', '07-605-1022', 'http://www.nknu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0015', '04-723-2105', '04-721-1098', 'http://www.ncue.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0017', '02-8674-1111', '02-8671-8000', 'http://www.ntpu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0018', '05-271-7000', '05-271-7095', 'https://www.ncyu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0019', '07-591-9000', '07-591-9083', 'http://www.nuk.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0020', '03-890-3000', '03-890-0111', 'https://www.ndhu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0021', '049-291-0960', '049-291-0413', 'http://www.ncnu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0022', '02-2733-3141', '02-2733-1044', 'https://www.ntust.edu.tw/home.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0023', '05-534-2601', '05-532-1719', 'http://www.yuntech.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0024', '08-770-3202', '08-770-2226', 'http://www.npust.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0025', '02-2771-2171', '02-2781-5578', 'https://www.ntut.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0028', '02-2896-1000', '02-2893-8845', 'http://www.tnua.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0029', '02-2272-2181', '02-2969-4830', 'http://www.ntua.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0030', '089-318-855', '089-517-316', 'http://www.nttu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0031', '03-935-7400', '03-935-9339', 'http://www.niu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0032', '037-382-000', '037-331-165', 'http://www.nuu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0033', '05-631-5000', '05-631-5999', 'http://www.nfu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0035', '06-693-0100', '06-693-0121', 'http://www.tnnua.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0036', '06-213-3111', '06-214-4409', 'http://www.nutn.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0037', '02-2732-1104', '02-2733-0473', 'http://www.ntue.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0039', '04-2218-3199', '04-2218-3180', 'http://www.ntcu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0042', '06-926-4115', '06-926-4265', 'http://www.npu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0043', '04-2392-4505', '04-2392-3663', 'https://www.ncut.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0044', '03-328-3201', '03-328-4047', 'http://www.ntsu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0046', '02-2822-7101', '02-2822-9389', 'http://www.ntunhs.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0047', '07-806-0505', '07-806-1473', 'http://www.nkuht.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0048', '082-313-300', '082-313-304', 'http://www.nqu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0049', '04-2221-3108', '04-2223-2463', 'https://www.ntus.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0050', '04-2219-5678', '04-2219-5011', 'http://www.nutc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0051', '02-3322-2777', '02-2322-6109', 'https://www.ntub.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0052', '08-766-3800', '08-723-4406', 'http://www.nptu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0053', '07-381-4526', '07-383-8435', 'http://www.nkust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0144', '02-2796-2666', '02-2794-1529', 'http://www.tcpa.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0221', '06-211-0600', '06-241-1065', 'http://www.ntin.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0222', '089-226-389', '089-225-185', 'http://www.ntc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('0A01', '02-2282-9355', '02-2288-6061', 'http://www.nou.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1001', '04-2359-0121', '04-2350-0847', 'http://www.thu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1002', '02-2905-2000', '02-2903-9809', 'http://www.fju.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1003', '02-2881-9471', '02-2882-1522', 'http://www.scu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1004', '03-265-9999', '03-265-8888', 'http://www.cycu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1005', '02-2621-5656', '02-2622-3204', 'http://www.tku.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1006', '02-2861-0511', '02-2861-5031', 'http://www.pccu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1007', '04-2451-7250', '04-2451-0081', 'http://www.fcu.edu.tw/wSite/mp?mp=1', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1008', '04-2632-8001', '04-2631-1170', 'https://www.pu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1009', '03-211-8800', '03-211-8700', 'http://www.cgu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1010', '03-463-8800', '03-463-8900', 'http://www.yzu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1011', '03-537-4281', '03-537-3771', 'http://www.chu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1012', '04-851-1888', '04-851-1666', 'http://www.dyu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1013', '02-2663-2102', '02-2663-3234', 'http://www.hfu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1014', '07-657-7711', '07-657-7056', 'http://www.isu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1015', '02-2236-8225', '02-2236-5133', 'https://www.shu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1016', '02-2882-4564', '02-2882-0521', 'http://www.mcu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1017', '02-2538-1111', '02-2533-6293', 'http://www.usc.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1018', '04-2332-3000', '04-2332-9898', 'http://www.cyut.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1019', '07-312-1101', '07-321-2062', 'https://www.kmu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1020', '05-272-1001', '05-242-7147', 'http://www.nhu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1021', '02-2621-2121', '02-2623-5533', 'http://www.au.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1022', '02-2182-2928', '02-2585-5911', 'http://www.ttu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1023', '06-253-3131', '06-254-3031', 'http://www.stust.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1024', '06-272-7175', '06-205-9929', 'https://www.ksu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1025', '06-266-4911', '06-266-8920', 'https://www.cnu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1026', '07-615-8000', '07-615-8999', 'http://www.stu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1027', '03-856-5301', '03-856-2500', 'http://www.tcu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1028', '02-2736-1661', '02-2378-7795', 'http://www.tmu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1029', '04-2473-0022', '04-2475-9950', 'http://www.csmu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1030', '02-8209-3211', '02-8209-4650', 'http://www.lhu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1031', '07-781-1151', '07-782-8805', 'https://www.fy.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1032', '03-559-3142', '03-559-5142', 'http://www.must.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1033', '06-278-5123', '06-278-5555', 'http://www.cjcu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1034', '04-2631-8652', '04-2631-0744', 'http://www.hk.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1035', '04-2205-3366', '04-2206-0248', 'http://www.cmu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1036', '03-458-1196', '無', 'https://www.uch.edu.tw/index.htm', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1037', '07-735-8800', '07-731-5367', 'https://www.csu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1038', '03-451-5811', '03-451-3786', 'https://www.vnu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1039', '03-530-2255', '03-539-1226', 'http://www.hcu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1040', '04-711-1111', '04-711-1171', 'https://www.ctu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1041', '02-2908-9899', '02-2904-1914', 'http://www.mcut.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1042', '07-607-7777', '07-607-7788', 'https://www.kyu.edu.tw/kyunew4/index3.html', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1043', '08-762-4002', '08-762-3924', 'http://www.tajen.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1044', '02-2801-3131', '02-2801-3021', 'http://www.sju.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1045', '04-2389-2088', '04-2389-5293', 'http://www.ltu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1046', '02-2931-3416', '02-8931-8847', 'http://www.cute.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1047', '04-2239-1647', '04-2239-5751', 'https://www.ctust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1048', '04-2332-3456', '04-2331-6699', 'http://www.asia.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1049', '03-341-2500', '03-341-2897#1710', 'http://www.knu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1050', '03-987-1000', '03-987-4815', 'http://www.fgu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1051', '06-253-2106', '06-254-9527', 'http://www.tut.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1052', '06-597-9566', '06-597-7050', 'http://www.feu.edu.tw/web/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1053', '03-538-1183', '03-538-5353', 'https://www.ypu.edu.tw/index.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1054', '02-8212-2000', '02-8212-2199', 'https://www.just.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1055', '06-267-1214', '06-335-6723', 'https://www.hwai.edu.tw/index.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1056', '02-8662-5859', '02-2662-4052', 'http://www.tnu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1057', '02-2658-5801', '02-2658-2507', 'http://www.takming.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1058', '04-887-6660', '04-887-2271', 'http://www.mdu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1060', '049-256-3489', '049-256-1443', 'https://www.nkut.edu.tw/index.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1061', '02-2782-1862', '02-2788-9145', 'http://www.cust.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1062', '04-2701-6855', '04-2707-5420', 'https://www.ocu.edu.tw/index.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1063', '037-651-188', '037-651-201', 'https://www.ydu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1064', '08-779-9821', '08-779-9711', 'https://www.meiho.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1065', '05-226-7125', '05-206-3455', 'http://www.wfu.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1066', '05-537-0988', '05-537-0989', 'http://www.twu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1067', '06-571-8888', '06-572-2858', 'https://web.tsu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1068', '04-835-9000', '04-836-4191', 'http://www.ccut.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1069', '04-2496-1100', '04-2496-1187', 'http://www.hust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1070', '03-211-8999', '03-211-8866', 'https://www.cgust.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1071', '02-2892-7154', '02-2896-5951', 'http://www.tpcu.edu.tw/bin/home.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1072', '03-592-7700', '03-592-6006', 'http://www.mitust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1073', '02-2601-5310', '02-2601-0748', 'https://www.hwu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1075', '07-342-6031', '07-342-7942', 'http://www.wzu.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1076', '02-8941-5100', '02-2941-5730', 'https://www.hwh.edu.tw/bin/hwhhome.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1077', '03-857-2158', '03-857-7261', 'https://www.tcust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1078', '02-2257-6167', '02-2258-3710', 'https://www.chihlee.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1079', '02-2632-1181', '02-2632-8744', 'http://www.ukn.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1080', '02-2273-3567', '02-2273-3995', 'https://w5.hdut.edu.tw/app/home.php', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1081', '07-693-2011', '07-693-1611', 'http://www.tf.edu.tw/tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1082', '02-2423-7785', '02-2429-3639', 'http://www.cufa.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1083', '02-2805-9999', '02-2805-2796', 'https://www.tumt.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1084', '02-7738-8000', '02-7738-2678', 'https://www.aeust.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1125', '06-287-3335', '06-287-3536', 'http://www.ctbc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1148', '03-821-0888', '03-826-2916', 'http://www.dahan.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1159', '07-262-1941', '07-788-4341', 'http://www.fotech.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1168', '03-436-1070', '03-438-8198', 'http://www.nanya.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1182', '03-977-1997', '03-978-9899', 'http://www.fit.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1183', '02-2909-7811', '02-2296-8589', 'http://www.lit.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1185', '02-2437-2093', '02-2437-6209', 'http://www.cku.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1188', '05-222-3124', '05-225-2393', 'http://www.ttc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1195', '02-2636-0303', '02-2636-1134', 'http://www.mmc.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1196', '02-2498-0707', '02-2408-2317', 'http://www.dila.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1282', '02-2636-6799', '02-2636-8123', 'https://www.mkc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1283', '037-728-855', '037-730-936', 'https://www.jente.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1284', '07-697-9333', '07-697-9697', 'https://www.szmc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1285', '08-864-7367', '08-864-7123', 'http://www.tzuhui.edu.tw/main/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1286', '02-2219-1131', '02-2219-7718', 'http://www.ctcn.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1287', '06-622-6111', '06-622-6367', 'http://www.mhchcm.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1289', '07-381-1765', '07-381-1112', 'http://www.yuhing.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1291', '03-989-7396', '03-989-7386', 'http://www.smc.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1292', '03-411-7578', '03-411-7600', 'https://www.hsc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1293', '05-265-8880', '05-265-8913', 'http://www.cjc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R02', '02-2723-9500', '02-2722-4646', 'http://www.tbts.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R03', '02-2809-7661', '02-2809-6631', 'http://www.cct.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R04', '07-687-2129', '07-687-1938', 'http://www.iktc.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R05', '02-2882-2370', '02-2881-6940', 'http://www.tgst.edu.tw', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R06', '049-298-8675', '049-298-9314', 'http://www.iktcds.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R07', '06-237-1291', '06-234-6060', 'http://www.ttcs.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R08', '03-273-7477', '03-371-4703', 'http://wp.ces.org.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('1R09', '049-220-9418', '049-220-3351', 'http://www.wxc.org.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3002', '02-2311-3040', '02-2381-4067', 'http://www.utaipei.edu.tw/', NULL, NULL, NULL, NULL);
INSERT INTO SCHOOL_INFO (ID, TEL, FAX, WEB, CREATE_BY, CREATE_DATE, LAST_BY, LAST_DATE)
VALUES ('3A01', '07-801-2008', '07-806-6725', 'http://www.ouk.edu.tw', NULL, NULL, NULL, NULL);
